=head1 NAME

s3tool - Conduct various maintenance tasks on Amazon S3 data

=head1 SYNOPSIS

B<s3tool>
S<[OPTION] [COMMAND]>

=head1 DESCRIPTION

s3tool is a utility which can be used to conduct maintenance tasks on S3
data.

=head1 OPTIONS

=over 4

=item -v, --verbose

increase verbosity

=item -p, --progress

display progress of operation

=item -a, --access-key=E<lt>keyE<gt>

Amazon S3 access key

=item -s, --secret-key=E<lt>keyE<gt>

Amazon S3 secret key

=item -c, --cache-dir=E<lt>dirE<gt>

Directory where the bucket cache is stored

=item -w, --workers=E<lt>intE<gt>

Number of worker threads to use for regen_cache

=item B<-h>, B<--help>               show help

=back

=head1 COMMANDS

=over 4

=item buckets

List all s3 buckets

=item new_bucket E<lt>bucketE<gt>

Create a new s3 bucket

=item delete_bucket E<lt>bucketE<gt>

Delete an s3 bucket

=item bucket_size E<lt>bucketE<gt>

Return the size in bytes used by <bucket>

=item files E<lt>bucketE<gt>

List all files in <bucket>

=item delete_file E<lt>bucketE<gt> E<lt>fileE<gt>

Delete <file> from <bucket>

=back

=head1 AUTHOR

Josh Bressers

=head1 SEE ALSO

s4ync(1)

