=head1 NAME

s4ync - Sync files to Amazon's Simple Storage Service (S3)

=head1 SYNOPSIS

B<s4ync>
S<[OPTION] [SOURCE] [DESTINATION]>

=head1 DESCRIPTION

s4ync is a utility which can be used to store and retreive file data to and
from Amazon S3.

Either the SOURCE or DESTINATION should be an S3 bucket, specified with the
syntax s3:<bucketname>.  When the SOURCE is S3, a path may be provided to
sync files which match a given path.

=head1 OPTIONS

=over 4

=item -v, --verbose

Increase verbosity

=item -p, --progress

Display progress of backup

=item -a, --access-key=E<lt>keyE<gt>

Amazon S3 access key

=item -s, --secret-key=E<lt>keyE<gt>

Amazon S3 secret key

=item -e, --encrypt=E<lt>keyE<gt>

Key gpg should encrypt to

=item --delete

Delete extraneous files from the destination

=item -h, --help

Show help

=back

=head1 AUTHOR

Josh Bressers

=head1 SEE ALSO

s3tool(1)
